### PR TITLE
Use `getproperty` instead of type parameter to get names

### LINKED ISSUE #414: Does `Arrow.write` have an upper limit for the number of columns?
I could not find this documented:
```julia
using Arrow, DataFrames
df = DataFrame(("$i" => rand(1000) for i in 1:65536)...)
Arrow.write("out/df.arrow", df)
```
produces
```
julia> Arrow.write("data.arrow", df)
ERROR: MethodError: no method matching length(::Nothing)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:172
  length(::Union{Tables.AbstractColumns, Tables.AbstractRow}) at ~/.julia/packages/Tables/AcRIE/src/Tables.jl:180
  ...
Stacktrace:
 [1] makeschema(b::Arrow.FlatBuffers.Builder, sch::Tables.Schema{nothing, nothing}, columns::Arrow.ToArrowTable)
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:393
 [2] close(writer::Arrow.Writer{IOStream})
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:244
 [3] open(::Arrow.var"#122#123"{DataFrame}, ::Type, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:file,), Tuple{Bool}}})
   @ Base ./io.jl:386
 [4] #write#121
   @ ~/.julia/packages/Arrow/P0wVk/src/write.jl:57 [inlined]
 [5] top-level scope
   @ REPL[94]:1

caused by: MethodError: no method matching length(::Nothing)
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:58
  length(::Union{LinearAlgebra.Adjoint{T, S}, LinearAlgebra.Transpose{T, S}} where {T, S}) at ~/.julia/juliaup/julia-1.8.5+0.aarch64.apple.darwin14/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:172
  length(::Union{Tables.AbstractColumns, Tables.AbstractRow}) at ~/.julia/packages/Tables/AcRIE/src/Tables.jl:180
  ...
Stacktrace:
 [1] makeschema(b::Arrow.FlatBuffers.Builder, sch::Tables.Schema{nothing, nothing}, columns::Arrow.ToArrowTable)
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:393
 [2] makeschemamsg(sch::Tables.Schema{nothing, nothing}, columns::Arrow.ToArrowTable)
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:430
 [3] macro expansion
   @ ~/.julia/packages/Arrow/P0wVk/src/write.jl:198 [inlined]
 [4] macro expansion
   @ ./task.jl:454 [inlined]
 [5] write(writer::Arrow.Writer{IOStream}, source::DataFrame)
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:185
 [6] (::Arrow.var"#122#123"{DataFrame})(writer::Arrow.Writer{IOStream})
   @ Arrow ~/.julia/packages/Arrow/P0wVk/src/write.jl:58
 [7] open(::Arrow.var"#122#123"{DataFrame}, ::Type, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:file,), Tuple{Bool}}})
   @ Base ./io.jl:384
 [8] #write#121
   @ ~/.julia/packages/Arrow/P0wVk/src/write.jl:57 [inlined]
 [9] top-level scope
   @ REPL[94]:1
```
Whereas it works with 65535 columns.

### PR DESCRIPTION
**Pull request by simsurace**
Closes #414 

`Tables.Schema` does not store names in the type parameters if there are more than `(2^16) - 1` columns: 

https://github.com/JuliaData/Tables.jl/blob/2cb13998e856692ed273c931b83477caf8b7b020/src/Tables.jl#L477-L483

### CODE REVIEW

**Comment by ericphanson** [comment]
Can you add a test?

**Comment by simsurace** [comment]
Sure. What do we want to test exactly? To prevent #414 we would need a table type that allows for >65535 columns.

**Comment by ericphanson** [comment]
Maybe this one? https://tables.juliadata.org/dev/#Tables.table

**Comment by simsurace** [comment]
Unfortunately (and maybe this is a bug in Tables.jl) `Tables.schema(::MatrixTable)` stores the names in the type parameter, so it won't expose the problem in #414.

**Comment by ericphanson** [comment]
Ah that does sound like a bug. Well, we can add a test-only dependency on DataFrames by adding it to extras & the test target in the Project.toml

**Comment by simsurace** [comment]
@ericphanson I added a test as suggested by you.

File: test/runtests.jl [hunk 1]
```diff
@@ -572,6 +572,17 @@ if pkgversion(ArrowTypes) >= v"2.0.2"
...
 
+# https://github.com/apache/arrow-julia/issues/414
+df = DataFrame(("$i" => rand(1000) for i in 1:65536)...)
+Arrow.write("df.arrow", df)
+df_load = Arrow.Table("df.arrow")
+@test Tables.schema(df) == Tables.schema(df_load)
+for (col1, col2) in zip(Tables.columns(df), Tables.columns(df_load))
+    @test col1 == col2
+end
+rm("df.arrow")
```
Comment (ericphanson) [inline test/runtests.jl:583]: We can roundtrip through serialization without actually writing to disk by using the helper `Arrow.tobuffer`:
```suggestion
df_load = Arrow.Table(Arrow.tobuffer(df))
@test Tables.schema(df) == Tables.schema(df_load)
for (col1, col2) in zip(Tables.columns(df), Tables.columns(df_load))
    @test col1 == col2
end
```

**Review by ericphanson — APPROVED** [review]

**Comment by simsurace** [comment]
Thanks for getting this merged quickly. What is the release cycle? Can we get this released as a patch?

**Comment by ericphanson** [comment]
There is a process documented partly here: https://github.com/apache/arrow-julia/tree/main/dev/release. It takes a day or two since there needs to be a vote. Can you PR a patch bump to get it started? We can ask @kou if they are willing to work on the next steps after.

**Comment by simsurace** [comment]
I'll do that once I get back to my computer.
